name: Mirror to GitLab

on: [push, delete]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@gitlab.com:YOUR_GITLAB_USERNAME/YOUR_REPO_NAME.git
          ssh_private_key:
            ${{ -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACD+EL1oEv5MADqGCi3Ol6aKDHbdtPN8C7+kk9AxnhegfwAAAJhMVO7cTFTu
3AAAAAtzc2gtZWQyNTUxOQAAACD+EL1oEv5MADqGCi3Ol6aKDHbdtPN8C7+kk9Axnhegfw
AAAEAgId/oVGQ7cQ/t7cgyFszMxVhlWfVUol30hSqB9UxE3f4QvWgS/kwAOoYKLc6XpooM
dt2083wLv6ST0DGeF6B/AAAAEGtpYW5ATWFjLmh0LmhvbWUBAgMEBQ==
-----END OPENSSH PRIVATE KEY----- }}